import type { NtfyConfig } from "../../Modules/PushNotifications/NtfyNotifier.js";
import type { PushStatePathResolution } from "../../Modules/PushNotifications/PushStatePath.js";
import type { LoggerLevel } from "../../Shared/Logging/Logger.js";

export interface ServerRuntimeConfiguration {
  logLevel: LoggerLevel;
  host: string;
  port: number;
  historyLimit: number;
  historyPayloadSummaryMaximumBytes: number;
  userAgent: string;
  runtimeStateSnapshotCacheTimeToLiveMs: number;
  ipcReconnectDelayMs: number;
  ntfyCompletionDebounceMs: number;
  capabilityListTimeoutMs: number;
  threadListAdapterTimeoutMs: number;
  pushTestSendTimeoutMs: number;
  traceDirectoryPath: string;
  defaultWorkspacePath: string;
  apiTokenHeaderName: string;
  apiTokenResponseHeader: string;
  apiSessionCookieName: string;
  apiSessionTimeToLiveMs: number;
  apiSessionSigningSecret: string;
  apiSessionSecureCookie: boolean;
  clientRequestIdHeaderName: string;
  clientRequestIdResponseHeader: string;
  clientActionIdHeaderName: string;
  clientActionIdResponseHeader: string;
  clientActionNameHeaderName: string;
  clientActionNameResponseHeader: string;
  apiToken: string;
  apiAuthRequired: boolean;
  pushEnabled: boolean;
  pushPrivateModeDefault: boolean;
  pushReceiptsMaxCount: number;
  pushReceiptsMaxAgeDays: number;
  threadListAggregationCacheTimeToLiveMs: number;
  threadListAggregationCacheMaximumEntries: number;
  webHealthBuildId: string;
  webHealthServiceWorkerVersion: string | null;
  appServerBaseEnvironment: NodeJS.ProcessEnv;
  codexExecutablePath: string;
  ipcSocketPath: string;
  gitCommit: string | null;
  pushStatePathResolution: PushStatePathResolution;
  pushReceiptsPath: string;
  pushSendsPath: string;
  pushLocalCaSourcePath: string;
  pushVapidPublicKey: string;
  pushVapidPrivateKey: string;
  pushVapidSubject: string;
  clientErrorSessionStartedAt: string;
  clientErrorSessionTimestamp: string;
  clientErrorSessionId: string;
  clientErrorLogPath: string;
  clientErrorMaxEntries: number;
  invalidThreadStreamEventsLogPath: string;
  ntfyConfiguration: NtfyConfig;
}
