#!/usr/bin/env node

import fs from "node:fs";
import path from "node:path";
import { createInterface } from "node:readline/promises";
import { parse } from "dotenv";
import { z } from "zod";

const cwd = process.cwd();
const envLocalPath = path.join(cwd, ".env.local");
const interactive = Boolean(process.stdin.isTTY && process.stdout.isTTY);

const managedKeys = new Set([
  "NTFY_ENABLED",
  "NTFY_TOPIC",
  "NTFY_BASE_URL",
  "NTFY_BEARER_TOKEN"
]);

const TopicSchema = z
  .string()
  .min(1)
  .refine((value) => !value.includes("/"), "Topic must not contain '/'");

const BaseUrlSchema = z.string().url();

function printHelp() {
  process.stdout.write(
    [
      "Usage: bun run setup:ntfy -- [--topic=<name>] [--base-url=<url>] [--token=<bearer>] [--disable]",
      "",
      "Examples:",
      "  bun run setup:ntfy",
      "  bun run setup:ntfy -- --topic=my-farfield",
      "  bun run setup:ntfy -- --topic=my-farfield --base-url=https://ntfy.sh",
      "  bun run setup:ntfy -- --disable"
    ].join("\n")
  );
  process.stdout.write("\n");
}

function normalizeOptional(value) {
  if (!value) {
    return null;
  }
  const normalized = value.trim();
  return normalized.length > 0 ? normalized : null;
}

function parseArgs(argv) {
  const result = {
    topic: null,
    baseUrl: null,
    token: null,
    disable: false
  };

  for (let index = 0; index < argv.length; index += 1) {
    const arg = argv[index];
    if (!arg || arg === "--") {
      continue;
    }
    if (arg === "--help" || arg === "-h") {
      printHelp();
      process.exit(0);
    }
    if (arg === "--disable") {
      result.disable = true;
      continue;
    }

    if (arg === "--topic" || arg === "--base-url" || arg === "--token") {
      const nextArg = argv[index + 1];
      if (!nextArg || nextArg.startsWith("--")) {
        throw new Error(`Missing value for ${arg}`);
      }
      if (arg === "--topic") {
        result.topic = nextArg;
      } else if (arg === "--base-url") {
        result.baseUrl = nextArg;
      } else {
        result.token = nextArg;
      }
      index += 1;
      continue;
    }

    if (arg.startsWith("--topic=")) {
      result.topic = arg.slice("--topic=".length);
      continue;
    }
    if (arg.startsWith("--base-url=")) {
      result.baseUrl = arg.slice("--base-url=".length);
      continue;
    }
    if (arg.startsWith("--token=")) {
      result.token = arg.slice("--token=".length);
      continue;
    }

    throw new Error(`Unknown argument: ${arg}`);
  }

  return result;
}

function loadEnvLocal() {
  if (!fs.existsSync(envLocalPath)) {
    return {};
  }
  return parse(fs.readFileSync(envLocalPath, "utf8"));
}

function writeEnvLocal(existingEntries, managedEntries) {
  const preservedEntries = Object.entries(existingEntries).filter(([key]) => !managedKeys.has(key));
  const lines = [
    "# Generated by: bun run setup:ntfy",
    "# Optional ntfy notification settings for Farfield.",
    ""
  ];

  for (const [key, value] of managedEntries) {
    lines.push(`${key}=${value}`);
  }

  if (preservedEntries.length > 0) {
    lines.push("", "# Preserved entries");
    for (const [key, value] of preservedEntries) {
      lines.push(`${key}=${value}`);
    }
  }

  fs.writeFileSync(envLocalPath, `${lines.join("\n")}\n`, "utf8");
}

async function promptInteractive(existingValues) {
  const rl = createInterface({
    input: process.stdin,
    output: process.stdout
  });

  try {
    const defaultEnabled = (existingValues["NTFY_ENABLED"] ?? "false").trim().toLowerCase() === "true";
    const enableRaw = await rl.question(
      `Enable ntfy notifications? (${defaultEnabled ? "Y/n" : "y/N"}): `
    );
    const enableNormalized = enableRaw.trim().toLowerCase();
    const enabled = enableNormalized.length === 0
      ? defaultEnabled
      : enableNormalized === "y" || enableNormalized === "yes";
    if (!enabled) {
      return {
        enabled: false,
        topic: null,
        baseUrl: null,
        token: null
      };
    }

    const defaultTopic = normalizeOptional(existingValues["NTFY_TOPIC"]) ?? "farfield";
    const topicRaw = await rl.question(`Topic [${defaultTopic}]: `);
    const topic = TopicSchema.parse(normalizeOptional(topicRaw) ?? defaultTopic);

    const defaultBaseUrl = normalizeOptional(existingValues["NTFY_BASE_URL"]) ?? "https://ntfy.sh";
    const baseUrlRaw = await rl.question(`Base URL [${defaultBaseUrl}]: `);
    const baseUrl = BaseUrlSchema.parse(normalizeOptional(baseUrlRaw) ?? defaultBaseUrl);

    const defaultToken = normalizeOptional(existingValues["NTFY_BEARER_TOKEN"]) ?? "";
    const tokenRaw = await rl.question(
      defaultToken.length > 0 ? "Bearer token [existing set, press Enter to keep]: " : "Bearer token (optional): "
    );
    const token = tokenRaw.trim().length === 0 ? (defaultToken.length > 0 ? defaultToken : null) : tokenRaw.trim();

    return {
      enabled: true,
      topic,
      baseUrl,
      token
    };
  } finally {
    rl.close();
  }
}

async function main() {
  const args = parseArgs(process.argv.slice(2));
  const existingEnv = loadEnvLocal();

  let desired;
  if (args.disable) {
    desired = {
      enabled: false,
      topic: null,
      baseUrl: null,
      token: null
    };
  } else if (args.topic || args.baseUrl || args.token) {
    const topic = TopicSchema.parse(
      normalizeOptional(args.topic) ?? normalizeOptional(existingEnv["NTFY_TOPIC"]) ?? "farfield"
    );
    const baseUrl = BaseUrlSchema.parse(
      normalizeOptional(args.baseUrl) ?? normalizeOptional(existingEnv["NTFY_BASE_URL"]) ?? "https://ntfy.sh"
    );
    const token = normalizeOptional(args.token) ?? normalizeOptional(existingEnv["NTFY_BEARER_TOKEN"]);
    desired = {
      enabled: true,
      topic,
      baseUrl,
      token
    };
  } else if (interactive) {
    desired = await promptInteractive(existingEnv);
  } else {
    const existingEnabled = (existingEnv["NTFY_ENABLED"] ?? "false").trim().toLowerCase() === "true";
    const existingTopic = normalizeOptional(existingEnv["NTFY_TOPIC"]);
    const existingBaseUrl = normalizeOptional(existingEnv["NTFY_BASE_URL"]) ?? "https://ntfy.sh";
    const existingToken = normalizeOptional(existingEnv["NTFY_BEARER_TOKEN"]);
    desired = {
      enabled: existingEnabled && existingTopic !== null,
      topic: existingTopic,
      baseUrl: existingBaseUrl,
      token: existingToken
    };
  }

  const managedEntries = desired.enabled
    ? [
        ["NTFY_ENABLED", "true"],
        ["NTFY_TOPIC", desired.topic],
        ["NTFY_BASE_URL", desired.baseUrl],
        ...(desired.token ? [["NTFY_BEARER_TOKEN", desired.token]] : [])
      ]
    : [["NTFY_ENABLED", "false"]];

  writeEnvLocal(existingEnv, managedEntries);

  if (!desired.enabled) {
    process.stdout.write("ntfy notifications disabled in .env.local\n");
    return;
  }

  process.stdout.write(
    [
      "ntfy notifications configured in .env.local",
      `- topic: ${desired.topic}`,
      `- base url: ${desired.baseUrl}`,
      desired.token ? "- bearer token: set" : "- bearer token: not set"
    ].join("\n")
  );
  process.stdout.write("\n");
}

main().catch((error) => {
  const message = error instanceof Error ? error.message : String(error);
  process.stderr.write(`[setup:ntfy] ${message}\n`);
  process.exit(1);
});
